const states = [
  "Andaman and Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattishgarh",
  "Chandigarh",
  "Daman and Diu",
  "Delhi",
  "Dadra and Nagar Haveli",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Jammu and Kashmir",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Maharashtra",
  "Madhya Pradesh",
  "Meghalaya",
  "Mizoram",
  "Manipur",
  "Nagaland",
  "Orissa",
  "Punjab",
  "Puducherry",
  "Rajasthan",
  "Sikkim",
  "Telangana",
  "Tamilnadu",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Ladakh",
  "uttarakhand"
];

export default states;
